chore(pre-push): add test

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -16,6 +16,18 @@ done
 cd $(dirname ${BASH_SOURCE[0]}) && cd ../  # shell script의 주소로 이동후 프로젝트 루트로 이동
 SCRIPT_DIR=`pwd` # shell script의 주소 저장
 
+./gradlew clean test
+if [ $? -eq 0 ]; then
+  echo "================================"
+  echo "Test has successfully completed"
+  echo "================================"
+else
+  echo "================================"
+  echo "Fail to test"
+  echo "================================"
+  exit 1
+fi
+
 ./gradlew check
 if [ $? -eq 0 ]; then
   echo "================================"
